spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  properties:
    active: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    #jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1 추가 시 프로그램 끝내도 메모리에 계속 상주
    #jdbc:h2~/test;DB_CLOSE_ON_EXIT=FALSE DB가 자동으로 종료되는 것을 막아줌
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none # 이것을 추가해야 schema.sql 자동으로 서치 가능하다고 한다

#      application.properties에 추가한 jpa 옵션 중 주의 깊게 봐야 할 설정은 DDL AUTO 옵션이다. spring.jpa.hibernate.
#      ddl-auto 옵션을 통해 애플리케이션 구동 시 JPA의 데이터베이스 초기화 전략을 설정할 수 있다. 총 5개의 옵션이 있다.
#
#      none: 사용하지 않음
#      create: 기존 테이블 삭제 후 테이블 생성
#      create-drop: 기존 테이블 삭제 후 테이블 생성, 종료 시점에 테이블 삭제
#      update: 변경된 스키마 적용
#      validate: 엔티티와 테이블 정상 매핑 확인


