spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/prod;AUTO_SERVER=true
    username: root
    password: root
    driver-class-name: org.h2.Driver

# JdbcTemplate logging level
logging:
  level:
    org:
      springframework:
        jdbc: debug