spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;DB_CLOSE_DELAY=-1;AUTO_SERVER=true
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

logging:
  pattern:
    file: "%-5level %d{yyyy-MM-dd HH:mm:ss} [%thread] %logger[%method:%line] - %msg%n"
  logback:
    rolling policy:
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}_%i.zip"
  file:
    name: log/roomEscape
  level:
    root: INFO
