spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    drive_class_name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      schema-locations: classpath:schema.sql




