spring:
  h2:
    console:
      enabled: true
#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:~/test;AUTO_SERVER=true
#      # 또는 jdbc:h2:tcp://localhost:9092/./data/testdb
#      driver-class-name: org.h2.Driver
#      username: sa
