spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/test
    username: sa
    driver: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:reservation/schema.sql