spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prod?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rootroot

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:/db/test
    username: root
    password: root
