TRUNCATE TABLE THEME;
TRUNCATE TABLE RESERVATION;

ALTER TABLE THEME ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE RESERVATION ALTER COLUMN ID RESTART WITH 1;

INSERT INTO theme (NAME, DESC, PRICE) VALUES ('Test Theme', 'Lorem Ipsum', 10000);
INSERT INTO reservation (DATE, TIME, NAME, THEME_ID) VALUES ('2023-01-01', '11:00:00', 'Tester', 1);