CREATE TABLE IF NOT EXISTS reservation (
    id bigint generated by default as identity,
    date varchar(100) NOT NULL,
    time varchar(100) NOT NULL,
    name varchar(100) NOT NULL,
    theme_name varchar(100) NOT NULL,
    theme_desc varchar(100) NOT NULL,
    theme_price int NOT NULL
);